### ISSUE TITLE
中国商品编码信息查询有问题

### ISSUE THREAD

**Issue by wuxianghou** [BreadKid/SearchItem#1]
现在商品编码中心添加了人机验证，这个怎么破

**Comment by BreadKid** [comment]
可能是最近新加的，我看看先

**Comment by BreadKid** [comment]
谢谢亲～～～～～～～目前我只能先换接口，如果你有自己觉得比较好用的接口可以直接换上去，反正扫描完后的编码值你知道在哪段代码获取是吧？
