### ISSUE TITLE
有两个小问题请教一下

### ISSUE THREAD

**Issue by ghost** [BreadKid/SearchItem#2]
因为时间比较急，还忘见谅
1、检测的入口在哪
2、能不能在返回结果中取到二维码三个黑块的点的坐标
ps:新人一枚还望不吝赐教

**Comment by BreadKid** [comment]
检测，你指的是条码的识别嘛？
条码的识别在CaptureActivity.java/onResume() 100行喔；
二维码三个黑块的点的坐标可以参考CaptureActivity.java/initCrop() 236行喔，更多的Zxing功能参考官网，我在readme里有link
另，我的分类和注释很完善，问这样的问题，筒靴你完全没有看过代码喔，一记头踏！
